Pearogram/Pearogram/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace Pearogram.Controllers
{
    public class ProductController : Controller
    {
        public ProductController(IProductRepository repository, IMapper mapper)
        {
            Repository = repository;
            Mapper = mapper;
        }

        public IProductRepository Repository { get; }
        public IMapper Mapper { get; }
        #region Show all products
        public IActionResult Index()
        {
            var produts = Repository.GetAll();
            return View(produts);
        }
        #endregion
        #region Update
        public async Task<IActionResult> Update(int id)
        {
            Product product = await Repository.GetById(id);
            return View(product);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Update(Product product)
        {
            int x = await Repository.Update(product);
            return RedirectToAction(nameof(Index), Repository.GetAll());
        }
        #endregion

        #region Delete
        public async Task<IActionResult> Delete(int id)
        {
            Product p = await Repository.GetById(id);
            if (p != null)
            {
                Repository.Delete(p);
            }
            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region Insert
        public IActionResult Insert()
        {
            return View();
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Insert(Product p)
        {
            if (ModelState.IsValid)
            {
                await Repository.Add(p);
                return RedirectToAction(nameof(Index));
            }
            return View(p);
        }
        #endregion

        #region Validation
        public async Task< IActionResult >IsExists(string productName , int SupplierID)
        {
            Product p =await Repository.GetByName(productName);
            if (p != null && p.SupplierID == SupplierID)
                return Json(false);
            return Json(true);
        }
        #endregion
    }
}

Pearogram/Pearogram/Controllers/SupplierController.cs
using Microsoft.AspNetCore.Mvc;

namespace Pearogram.Controllers
{
    public class SupplierController : Controller
    {
        public SupplierController(ISupplierRepository repository)
        {
            Repository = repository;
        }

        public ISupplierRepository Repository { get; }
        #region Show all Suppliers
        public IActionResult Index()
        {
            var supplier =  Repository.GetAll();
            return View(supplier);
        }
        #endregion
        #region Update
        public async Task<IActionResult> Update(int id)
        {
            Supplier supplier = await Repository.GetById(id); 
            return View(supplier);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Update(Supplier supplier)
        {
        if (ModelState.IsValid)
        {
            int x = await Repository.Update(supplier);
            return RedirectToAction(nameof(Index), Repository.GetAll());
            }
            return View(supplier);
        }
        #endregion

        #region Delete
        public async Task<IActionResult> Delete(int id)
        {
            Supplier s = await Repository.GetById(id);
            if (s != null)
            {
                Repository.Delete(s);
            }
            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region Insert
        public IActionResult Insert()
        {
            return View();
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Insert(Supplier s)
        {
            if (ModelState.IsValid)
            {
                await Repository.Add(s); 
                return RedirectToAction(nameof(Index));
            }
            return View(s);
        }
        #endregion
        #region Remote Check unique Supplier Name
        public async Task<IActionResult> UniqueSupplier(string SupplierName)
        {
            Supplier s = await Repository.GetByName(SupplierName);
            if (s == null)
                return Json( true);
            return Json(false);
        }
        #endregion

    }
}

Pearogram/Pearogram/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Pearogram</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pearogram.styles.css" asp-append-version="true" />
    @RenderSection("datatable" , false) 
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pearogram</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark btn btn-outline-light" asp-controller="Supplier" asp-action="index">Supplier</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark btn btn-outline-light" asp-controller="Product" asp-action="index">Product</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Pearogram - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>